#!/usr/bin/expect -f
#-------------------------------------------------- about us
set loginuser "root" 
set loginpass {XXXXX}


set ipaddr XXX.XXX.XXX.XXX
#[lrange $argv 0 0] 
set timeout 300
set cmd_prompt "]#|~]?"


#-------------------------------------------------- login by ssh 
spawn ssh $loginuser@$ipaddr
set timeout 300
expect {
-re "Are you sure you want to continue connecting (yes/no)?" {
send "yes\r"
} -re "assword:" {
send "${loginpass}\r"
} -re "Permission denied, please try again." {
exit
} -re "Connection refused" {
exit
} timeout {
exit
} eof {
exit
}
}


expect {
-re "assword:" {
send "$loginpass\r"
}
-re $cmd_prompt {
send "\r"
}
}


#---------------------------------------------------- now,we do some commands
#exec sleep 1
expect {
-re $cmd_prompt {
send "cd /home/chenzhen\r"
}
}


#exit
interact
